---
title: "p8105_hw5_bg2645"
author: "Bing Bing Guo"
date: "11/6/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rvest)
library(tidyverse)
library(purrr)
library(broom)
```


## Problem 1 
```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```
* For numeric variables,replace "NA" with the mean of non-missing values. For character variables, replace "NA" with "virginica".
```{r} 
insert_new = function(x) {
  if(is.numeric(x) == TRUE) {
    x = x %>%
      replace_na(mean(x, na.rm = TRUE))
  }
  
else if(is.character(x) == TRUE){
  x = x %>%
    replace_na("virginica")
 }

return(x)

}

iris_with_missing = map_df(iris_with_missing,insert_new) 

iris_with_missing
```

## Problem 2 
* Create a tidy dataframe containing data from all participants, including the subject ID, arm, and observations over time
```{r} 
longstudy_files = list.files(path = "./data",full.names = TRUE) %>% 
  map(read.csv) %>% 
  reduce(rbind) %>% 
  janitor::clean_names() %>%
  mutate(subject_id = c(1:20), 
         arm = ifelse(subject_id == c(1:10), "control",
                     "experimental")) %>% 
  gather(key = week, value = observation, week_1:week_8) %>% 
  mutate(week = str_replace(week, "week_", ""))
```
* Make a spaghetti plot showing observations on each subject over time
```{r}
longstudy_files %>% 
  ggplot(aes(x = week, y = observation)) + 
  geom_line(aes(group = subject_id, color = arm)) + 
   labs(
    title = "Observation For Subjects Over Time",
    x = "Week",
    y = "Observation"
   )
```

## Problem 3 
```{r}
set.seed(1)
sim_regression = function(n=30, beta0 = 2, beta1 = 0) {
  sim_data = tibble(
    x = rnorm(n, mean=0, sd = 1),
    y = beta0 + beta1 * x + rnorm(n, 0, sqrt(50))
    )
  ls_fit = lm(y ~ x, data = sim_data)
}
```